In [3]:
class Persona:
    def __init__(self,nombre, edad):
        self.nombre = nombre
        self.edad   = edad

    def saludar(self):
        print(f'Hola me llamo {self.nombre} y tengo {self.edad} años')

ciudadano_1 = Persona("Aitziber", 24)
print(ciudadano_1.edad)
ciudadano_1.saludar()


class Estudiante(Persona):
    def __init__(self, nombre, edad, asignaturas):
        super().__init__(nombre, edad)
        self.asignaturas = asignaturas
    def saludar(self):
        asignatura_texto = ",".join(self.asignaturas)
        print(f'Hola me llamo {self.nombre} y curso {asignatura_texto}')

alumno_1 = Estudiante('Ana',22,['Ingles', 'Matematicas', 'Latin'])
alumno_1.saludar()




24
Hola me llamo Aitziber y tengo 24 años
Hola me llamo Ana y curso Ingles,Matematicas,Latin


In [4]:
import numpy as np
import matplotlib.pyplot as plt
import time

Fontconfig warning: ignoring UTF-8: not a valid region tag
Matplotlib is building the font cache; this may take a moment.


In [7]:
n = 1000
U = np.random.rand(n)
V = np.random.choice(range(5),n)

W = 0
t1 = time.time()
for i in range(n):
    W = W + U[i]*V[i]
t2 = time.time()
print(f'Solucion bucles {W}, calculada en {1000*(t2-t1)} ms')

w = 0
t1 = time.time()
W = np.dot(U,V)
t2 = time.time()
print(f'Solucion bucles {W}, calculada en {1000*(t2-t1)} ms')



Solucion bucles 963.179253962538, calculada en 1.0480880737304688 ms
Solucion bucles 963.1792539625393, calculada en 0.17905235290527344 ms


In [8]:
n = 1000
U = np.random.rand(n)
A = np.random.choice(range(1,5),(n,n))


V = np.zeros_like(U)
t1 = time.time()
for i in range(n):
    for j in range(n):
        V[i] = V[i] + A[i,j]*U[j]

t2 = time.time()
print(f'Solucion calculada en {1000*(t2-t1)} ms')



Solucion calculada en 1094.6519374847412 ms


In [9]:
n = 1000
X = np.linspace(-1, 1, n)
Y = np.zeros_like(X)

t1 = time.time()
for i in range(n):
    Y[i] = np.sin(X[i])
t2 = time.time()
print(1000*(t2-t1),'ms')

t1 = time.time()
Y = np.sin(X)
t2 = time.time()
print(1000*(t2-t1),'ms')



1.6071796417236328 ms
0.5321502685546875 ms


In [10]:
A = np.random.choice(range(1,6), (3,4))
for fila in A:
    print(fila)

A.T 
A@A.T

[4 5 3 4]
[4 5 3 5]
[4 4 4 5]


array([[66, 70, 68],
       [70, 75, 73],
       [68, 73, 73]])

In [11]:
U = np.random.choice(range(10),10)
k = 6
print(k+U)

[13 11  7 11 11 13 14 13  8 10]


In [17]:
A = np.random.choice(range(6),(5,4))
B = np.ones(4).reshape(1,4)

print(A)

[[1 3 2 5]
 [2 3 0 2]
 [3 4 1 3]
 [4 3 5 0]
 [1 2 1 1]]


In [14]:
C = A + B

print('A=', A, A.shape)
print('B=', B, B.shape)

A= [[4 2 2 1]
 [4 0 3 0]
 [4 5 1 3]
 [0 5 4 1]
 [1 3 3 3]]
B= [1. 1. 1. 1.]
